import {
  Bricolage_Grotesque,
  DM_Sans,
  Geist_Mono,
  Inter,
} from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";

const dmSans = DM_Sans({
  variable: "--font-dm-sans",
  subsets: ["latin"],
  weight: ["400", "500", "700"],
  display: "swap",
});

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
  display: "swap",
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const grotesque = Bricolage_Grotesque({
  variable: "--font-grotesque",
  subsets: ["latin"],
  weight: ["400", "500", "700"],
  display: "swap",
});

/** @type {import("next/dist/compiled/@next/font").NextFontWithVariable[]} */
const fonts = [dmSans, inter, geistMono, grotesque];

/** @type {import("next").Metadata} */
export const metadata = {
  title: "Create Loafy App - Next.js Template",
  description: "Generated by Loafy",
};

/** @param {Readonly<{ children: React.ReactNode }>} param0 */
export default function RootLayout({ children }) {
  return (
    <html>
      <body
        className={cn(
          fonts.map((font) => font.variable).join(" "),
          "antialiased"
        )}
      >
        {children}
      </body>
    </html>
  );
}
