import type { Metadata } from "next";
import {
  Bricolage_Grotesque,
  DM_Sans,
  Geist_Mono,
  Inter,
} from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";

const dmSans = DM_Sans({
  variable: "--font-dm-sans",
  subsets: ["latin"],
  weight: ["400", "500", "700"],
  display: "swap",
});

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
  display: "swap",
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const grotesque = Bricolage_Grotesque({
  variable: "--font-grotesque",
  subsets: ["latin"],
  weight: ["400", "500", "700"],
  display: "swap",
});

const fonts = [dmSans, inter, geistMono, grotesque];

export const metadata: Metadata = {
  title: "Create Loafy App - Next.js Template",
  description: "Generated by Loafy",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html>
      <body
        className={cn(
          fonts.map((font) => font.variable).join(" "),
          "antialiased"
        )}
      >
        {children}
      </body>
    </html>
  );
}
